# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
    profile: "chill"
    request_changes_workflow: false
    changed_files_summary: false
    high_level_summary: false
    poem: false
    review_status: true
    collapse_walkthrough: false
    sequence_diagrams: false
    related_prs: false
    auto_review:
        enabled: true
        drafts: false
chat:
    auto_reply: true
