name: Build Docker image
on:
    push:
        branches:
            - main
jobs:
    docker:
        if: github.repository == 'OpenWF/SpaceNinjaServer'
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to container registry
              uses: docker/login-action@v3
              with:
                  username: openwf
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: |
                      openwf/spaceninjaserver:latest
                      openwf/spaceninjaserver:latest-arm64
                      openwf/spaceninjaserver:${{ github.sha }}
                      openwf/spaceninjaserver:${{ github.sha }}-arm64
