name: Build Docker image
on:
  push:
    branches:
      - main
jobs:
    docker:
        if: github.repository == 'spaceninjaserver/SpaceNinjaServer'
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Log in to container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                push: true
                tags: |
                  ghcr.io/spaceninjaserver/spaceninjaserver:latest
                  ghcr.io/spaceninjaserver/spaceninjaserver:${{ github.sha }}
